#pragma once

#include <algorithm>
#include <cstdint>
#include <cmath>
#include <memory>
#include <unordered_map>
#include <vector>

#include <glm/glm.hpp>

#include "Collider.h"
#include "CollisionDetector.h"
#include "ContactSolver.h"
#include "ContinuousCollision.h"
#include "ContactManifold.h"
#include "Integrator.h"
#include "PhysicsMaterial.h"
#include "RigidBody.h"

namespace Runtime {
namespace Physics {

class PhysicsWorld {
public:
	// Construct world with a default semi-implicit Euler integrator.
	PhysicsWorld();

	// Set and query global gravity acceleration.
	void SetGravity(const glm::vec3& gravity) { m_gravity = gravity; }
	const glm::vec3& Gravity() const { return m_gravity; }

	// Configure fixed simulation step length used by accumulator stepping.
	void SetFixedTimeStep(float dt) { m_fixedTimeStep = std::max(0.0001f, dt); }
	float FixedTimeStep() const { return m_fixedTimeStep; }

	// Enable/disable continuous collision detection for high-speed bodies.
	void SetContinuousCollisionEnabled(bool enabled) { m_enableCcd = enabled; }
	bool ContinuousCollisionEnabled() const { return m_enableCcd; }

	// Limit the maximum CCD sub-steps processed in one fixed step.
	void SetCcdMaxSubSteps(int steps) { m_ccdMaxSubSteps = std::max(1, steps); }
	int CcdMaxSubSteps() const { return m_ccdMaxSubSteps; }

	// Configure iterative contact solver pass count.
	void SetSolverIterations(int iterations) { m_solverIterations = std::max(1, iterations); }
	int SolverIterations() const { return m_solverIterations; }

	// Create a rigid body and return its unique runtime id.
	uint32_t CreateRigidBody(const RigidBodyDesc& desc);

	// Remove body and its attached collider if present.
	bool DestroyRigidBody(uint32_t bodyId);

	// Check body existence by id.
	bool HasRigidBody(uint32_t bodyId) const;

	// Get mutable or const body pointer; returns nullptr if missing.
	RigidBody* GetRigidBody(uint32_t bodyId);

	const RigidBody* GetRigidBody(uint32_t bodyId) const;

	// Attach or replace collider on a body.
	bool AttachCollider(uint32_t bodyId, const ColliderDesc& desc);

	// Remove collider from body.
	bool RemoveCollider(uint32_t bodyId);

	// Check collider existence by body id.
	bool HasCollider(uint32_t bodyId) const;

	// Get mutable or const collider pointer; returns nullptr if missing.
	Collider* GetCollider(uint32_t bodyId);

	const Collider* GetCollider(uint32_t bodyId) const;

	// Advance world time using accumulator-driven fixed steps.
	void Step(float deltaTime);

	// Get contacts generated by the latest solved step.
	const std::vector<ContactManifold>& Contacts() const { return m_contacts; }

	// Read-only access to body/collider containers.
	const std::unordered_map<uint32_t, RigidBody>& Bodies() const { return m_bodies; }
	const std::unordered_map<uint32_t, Collider>& Colliders() const { return m_colliders; }

private:
	// Integrate all bodies for one sub-step.
	void IntegrateBodies(float dt);

	// Re-detect and resolve contacts iteratively to improve stability.
	void SolveContactsIterative();

	// Execute one fixed simulation tick with optional CCD splitting.
	void FixedStep(float dt);

	// Resolve all current manifolds through the contact solver.
	void ResolveContacts();

	glm::vec3 m_gravity = glm::vec3(0.0f, -9.81f, 0.0f);
	float m_fixedTimeStep = 1.0f / 60.0f;
	float m_accumulator = 0.0f;
	uint32_t m_nextBodyId = 1;

	std::unordered_map<uint32_t, RigidBody> m_bodies;
	std::unordered_map<uint32_t, Collider> m_colliders;
	std::vector<ContactManifold> m_contacts;
	bool m_enableCcd = true;
	int m_ccdMaxSubSteps = 8;
	int m_solverIterations = 8;

	CollisionDetector m_collisionDetector;
	ContinuousCollisionDetector m_continuousCollision;
	ContactSolver m_contactSolver;
	std::unique_ptr<Integrator> m_integrator;
};

} // namespace Physics
} // namespace Runtime
